/*******************************************************************************
	Generated by: DLL to C version 3.91
	Date: 2024-11-14
	Description: The declaration of functions and variables for PI_GCS2_DLL.dll.
	Website: http://www.dll-decompiler.com
	Technical Support: support@dll-decompiler.com
*******************************************************************************/

#if !defined(_PI_GCS2_DLL_SUPP_H_005E2000_INCLUDED_)
#define _PI_GCS2_DLL_SUPP_H_005E2000_INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000


#include <windows.h>

#pragma pack(push)
#pragma pack(1)

__declspec(align(16)) struct stPI_GCS2_DLL
{
	UCHAR Header[0x1000];
	UCHAR Text[0x456000];
	UCHAR Rdata[0x10B000];
	UCHAR Data[0x2B000];
	UCHAR Tls[0x1000];
	UCHAR Rsrc[0x1000];
	UCHAR Reloc[0x53000];
};

#pragma pack(pop)

__declspec(align(16)) extern stPI_GCS2_DLL PI_GCS2_DLL;

/* Data for initialization. */
extern UCHAR PI_GCS2_DLL_InitData[0x9EFFA];

extern HMODULE g_hPI_GCS2_DLL;

/* Description: Initialize the DLL. */
BOOL PI_GCS2_DLL_Init();

/* Description: Load the DLL. */
BOOL PI_GCS2_DLL_LoadLibrary();

/* Description: Free the DLL. */
BOOL PI_GCS2_DLL_FreeLibrary();

/*
	Description: Access any address in the DLL.
	Parameters:
		rvaAddr: The RVA address you want to access.
*/
void* __stdcall PI_GCS2_DLL_RVA(DWORD rvaAddr);

#define PI_GCS2_DLL_VA(vaAddr) PI_GCS2_DLL_RVA((vaAddr) - 0x10000000)

/*
	Description: Retrieves the address of an exported function or variable in the DLL.
	Parameters:
		lpProcName: The function or variable name.
*/
FARPROC PI_GCS2_DLL_GetProcAddress(LPCSTR lpProcName);

#endif // !defined(_PI_GCS2_DLL_SUPP_H_005E2000_INCLUDED_)